### PR TITLE
Gfa paths

### PR DESCRIPTION
**Pull request by asl**
This PR provides an experimental support to load paths from GFA. One could then draw the graph along these paths (e.g. in SPAdes cases these are the scaffolds).

### CODE REVIEW

**Comment by ekg** [comment]
Could this be merged?

It's very useful.

**Comment by ekg** [comment]
@rrwick would it be better if we forked Bandage for future development?

**Comment by rlorigro** [comment]
I would also benefit quite a lot from being able to visualize paths, and I know several others in my lab would too.

**Comment by asl** [comment]
I went ahead and made a fork: https://github.com/asl/Bandage
Also, `qt6` branch contains port to qt6.

**Comment by rlorigro** [comment]
Cool, thanks. I am running into a couple issues when attempting to build on Ubuntu 20, using the qmake recipe from the Readme. 

I have resolved the first issue, which was actually on the main branch, and this link summarizes the issue and the working solution:
https://stackoverflow.com/a/52841306/5095925

The second issue is that when I switch to your gfa-paths branch, I am getting QT namespace-related errors, and I don't know if I can fix this on my own:
```
ui/mygraphicsview.cpp: In member function ‘QPointF MyGraphicsView::findIntersectionWithViewportBoundary(QLineF)’:
ui/mygraphicsview.cpp:243:14: error: ‘class QLineF’ has no member named ‘intersects’; did you mean ‘intersect’?
  243 |     if (line.intersects(boundary1, &intersection) == QLineF::BoundedIntersection)
      |              ^~~~~~~~~~
      |              intersect

```
It seems to suggest that references are being made to functions that come from a different version of qt? Here is nearly the same issue on stackoverflow again:
https://github.com/therecipe/qt/issues/750

**Comment by ekg** [comment]
@asl you should merge your gfa-paths changes into master on the fork. I'll be happy to contribute some powerups, for path position queries in particular. CC @andreaguarracino

**Comment by asl** [comment]
@rlorigro `gfa-paths` branch is still with "old" qt5. I will need to find some time to merge everything together :)

**Comment by rlorigro** [comment]
Hmm ok. I think it's actually not related to qt6, if that's what you mean

**Comment by asl** [comment]
It does. `intersects` is deprecated in Qt5 and was removed from Qt6. Everything else depends on the exact version of Qt + additional flags. See https://github.com/asl/Bandage/commit/03892efc17cf4fcdd7005a2d638d81ce5e83153a

**Comment by rlorigro** [comment]
I guess I am confused because I am attempting to build with QT_SELECT=5, and the issue i referenced (https://github.com/therecipe/qt/issues/750) seems to indicate that it is an error involving the qt5 library itself.

**Comment by rlorigro** [comment]
The issue may be that Ubuntu20.04 uses qt 5.12: https://packages.ubuntu.com/focal/qtbase5-dev so I guess I will try upgrading

**Comment by asl** [comment]
So, I went ahead and merged everything into 'dev' branch of https://github.com/asl/Bandage repo. Now with GFA paths and Qt6.

**Comment by ekg** [comment]
IMO you should merge this into your master and post a static binary
release. I'll publicize the fork and the path features. These will be
helpful to existing users of Bandage.

**Comment by asl** [comment]
The 'dev' branch is default in the fork to emphasize the status (note that it includes several commits and bugfixes from 'development' branch of rrwick/bandage that are absent from master). I do not have bandwidth to do any binary releases, etc. so feel free to contribute :)

**Comment by ekg** [comment]
Totally understand! Thanks for the patch. I'll look into what's needed for
a static build. If it's push button would you be able to post it? Or you
can add me as a collaborator on your repo.

**Comment by asl** [comment]
Closing as the project is not going to update anymore. Those who need paths might use https://github.com/asl/Bandage/ instead

**Pull request closed without merging**
